### ISSUE TITLE
[ERROR] console -  Caught exception: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wayne5ning** [NetEase/chatofpomelo-websocket#17]
# Test Environment
* Windows 10
* Node v0.12.7
* pomelo 1.1.9
* chrome 44.0.2403.130 m

# Problem
1 Successfully start game-server and web-server with default configurations.
2 log on http://127.0.0.1:3001/index.html, enter username and channel, click join.
3 game-server console outputs:
> [2015-08-11 10:02:06.260] [ERROR] console -  Caught exception: TypeError: Cannot convert undefined or null to object
>     at copyArray (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protocol.js:266:11)
>     at Object.Package.decode (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protocol.js:138:7)
>     at WebSocket.<anonymous> (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\lib\connectors\hybridsocket.js:40:21)
>     at WebSocket.emit (events.js:110:17)
>     at Receiver.self._receiver.onbinary (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\WebSocket.js:549:10)
>     at Receiver.opcodes.2.finish (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:448:14)
>     at Receiver.expectHandler (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:433:33)
>     at Receiver.add (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:93:24)
>     at Socket.firstHandler (e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\WebSocket.js:524:22)
>     at Socket.emit (events.js:107:17)
> [2015-08-11 10:02:06.266] [WARN] pomelo - [e:\tmp\chatofpomelo-websocket\game-server\node_modules\pomelo\lib\master\starter.js] child process exit with error, error code: 3221225477, executed command: C:\Program Files (x86)\nodejs\node.exe

# Similar issues
http://nodejs.netease.com/topic/5562c342710651e80fcd09f8

**Comment by wayne5ning** [comment]
Problem: Local pomelo has a version number of 1.0.4, which is not the latest (version=1.1.9).

With latest pomelo, no error occurred with join.
