### ISSUE TITLE
websocket无法建立连接

### ISSUE THREAD

**Issue by HeChenTao** [NetEase/chatofpomelo-websocket#19]
pomelo是1.2版本，运行官方示例。在创建连接时提示错误：

```
[2016-02-19 17:05:45.965] [ERROR] console -  Caught exception: TypeError: argument should be a Buffer
    at TypeError (native)
    at copyArray (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protocol.js:266:11)
    at Object.Package.decode (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protocol.js:138:7)
    at WebSocket.<anonymous> (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\lib\connectors\hybridsocket.js:40:21)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.self._receiver.onbinary (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\WebSocket.js:549:10)
    at Receiver.opcodes.2.finish (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:448:14)
    at Receiver.expectHandler (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:433:33)
    at Receiver.add (F:\pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:93:24)

```

**Comment by shuidong** [comment]
有同样问题。

**Comment by Bluebang** [comment]
怎么解决的？？？

**Comment by HeChenTao** [comment]
提了一个pr，没有被merge，可以参考解决
https://github.com/NetEase/pomelo-protocol/pull/8

**Comment by Bluebang** [comment]
在game-server下面把配置文件package.json修改一下pomelo版本就可以了。
{
	"name": "chatofpomelo-websocket",
	"version": "0.0.1",
	"private": false,
	"dependencies": {
		"pomelo": "1.1.8",//<=here
		"crc": "0.2.0"
	}
}
