### ISSUE TITLE
pomelo start error 

### ISSUE THREAD

**Issue by dongyado** [NetEase/chatofpomelo-websocket#23]
pomelo version: 2.2.5
node version: v7.8.0

[2017-04-14 17:40:01.934] [INFO] pomelo - [/home/slayer/workspace/chatofpomelo-websocket/game-server/node_modules/._pomelo@1.2.0@pomelo/lib/application.js] application inited: "master-server-1"

/home/slayer/workspace/chatofpomelo-websocket/game-server/node_modules/._socket.io@0.9.16@socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/slayer/workspace/chatofpomelo-websocket/game-server/node_modules/._socket.io@0.9.16@socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/slayer/workspace/chatofpomelo-websocket/game-server/node_modules/._socket.io@0.9.16@socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

**Comment by liangmuren** [comment]
pomelo version: 2.2.5
node version: v8.2.1

Same error.

**Comment by willerce** [comment]
@liangmuren try to use node v5.x start the game server

**Comment by dopefaceee** [comment]
@willerce im using v5.2.1 but it still give error.

**Comment by Sier-Kang** [comment]
python version

**Comment by elfstream** [comment]
pomelo version: 2.2.5
node version v8.9.4
Same error
the answer is here:
https://github.com/LearnBoost/websocket.io/issues/55
For short answer just change this:
var EventEmitter = process.EventEmitter;
into this:
var EventEmitter = require('events');

**Comment by realyibo** [comment]
same error. but i find a way to fix.
open game-server/package.json. Just change pomelo's version in dependencies to a new version.
My is "pomelo": "2.2.5". works fine!

**Comment by yutiya** [comment]
"pomelo": "2.2.5"
手动将game-server改成2.2.5即可

**Comment by lita-jerry** [comment]
一，首先修改game-server文件夹内的package.json文件，pomelo版本改为2.2.5
二，参考下我写的切换Node版本的文章：[Mac端更改、更新Node.js版本](https://jerrysir.github.io/2018/08/15/Mac%E7%AB%AF%E6%9B%B4%E6%94%B9%E3%80%81%E6%9B%B4%E6%96%B0Node-js%E7%89%88%E6%9C%AC/)

安装Node.js 8.11.3版本
`n 8`

切换到8.11.3版本
`n # 选择8.11.3`

删除game-server文件夹内的 node_modules文件夹 和 package-lock.json文件

返回上一层执行
`sh npm-install.sh`

it's working now

**Comment by calmchang** [comment]
> same error. but i find a way to fix.
> open game-server/package.json. Just change pomelo's version in dependencies to a new version.
> My is "pomelo": "2.2.5". works fine!

it`s work
