### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by iiccttff** [NetEase/chatofpomelo-websocket#27]
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.mkdir (fs.js:713:16)
    at start (/Users/circle/Documents/GitHub/NetEase/pomelo-master/bin/pomelo:347:8)
    at Command.<anonymous> (/Users/circle/Documents/GitHub/NetEase/pomelo-master/bin/pomelo:65:5)
    at Command.<anonymous> (/Users/circle/Documents/GitHub/NetEase/pomelo-master/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/Users/circle/Documents/GitHub/NetEase/pomelo-master/node_modules/commander/index.js:472:12)
    at Command.parse (/Users/circle/Documents/GitHub/NetEase/pomelo-master/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/Users/circle/Documents/GitHub/NetEase/pomelo-master/bin/pomelo:142:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by ChenEgou** [comment]
这坑好深，我也遇到了。
查遍了所有地方，找不到解决的方法。
我怀疑，是node的版本、或者是pomelo的版本有问题 。。
